
repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=88, --target-version=py37]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile=black, --line-length=88]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --remove-unused-variables]
-   repo: https://github.com/mypy/mypy
    rev: v1.0.0
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --strict]
